FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /srv/app

ENV PYTHONPATH=/srv/app

COPY app/requirements.txt /tmp/requirements.txt
RUN pip install --no-cache-dir -r /tmp/requirements.txt

COPY app /srv/app

CMD ["python", "-m", "uvicorn", "mtproxy_manager.admin.main:app", "--host", "0.0.0.0", "--port", "8080"]
